spring:
  cloud:
    gateway:
      routes:
        - id: Enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/enroll/**

        - id: Token-service
          uri: lb://TOKEN-SERVICE
          predicates:
            - Path=/generate/**

        - id: Partner-Service
          uri: lb://PARTNER-SERVICE
          predicates:
            - Path=/partner/**
#comment
  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/